// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateText('headerText', { text: 'New buyings:' });
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('backDone', { onclick: 'showFront', text: 'Done' });
    CreateText('text', { text: 'Server' });
    CreateText('text1', { text: 'Benutzer' });
    CreateText('text2', { text: 'Passwort' });
    CreateText('text3', { text: unescape('Serverdaten angeben und ab daf%u00FCr!') });
    CreateButton('buyButton', { text: 'Buy', onclick: 'submit_buyings', rightImageWidth: 5, leftImageWidth: 5 });
    CreateText('text4', { text: 'GitHub Project HP' });
}
window.addEventListener('load', setupParts, false);
