<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head profile="http://gmpg.org/xfn/11">
<base href="<?= $this->basepath ?>"/>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="description" content="description"/>
<meta name="keywords" content="keywords"/> 
<meta name="author" content="author"/> 
<title><?= $this->pageTitle ?></title>
<link rel="stylesheet" href="<?= $this->basepath ?>/style.css" type="text/css" media="screen" />
<link rel="stylesheet" href="<?= $this->basepath ?>/wg-organizer.css" type="text/css" media="screen" />
</head>

<body>

<div id="container">

	<div id="top">

		<div class="left">
			<h1 id="site_title"><?= $this->pageTitle ?></h1>
			<?php if ($this->currentResident): ?>
				<div id="site_description">Angemeldet als <?= $this->currentResident->getName(); ?></div>
			<?php endif; ?>
		</div>

		<!-- <a href="#" class="button feed right"><span></span></a>  -->
		

		<div class="clearer"></div>

	</div>

	<div class="path" id="nav">

		<?= $this->menue($this->mainMenue); ?>

		<div class="clearer"></div>

	</div>

	<div id="main">

		<div class="left" id="main_left">	
			<? if ( $this->flashMessenger->hasMessages() ): ?>
			<div id="messages">
				<ul>
				<? foreach($this->flashMessenger->getMessages() as $msg): ?>
					<li><?= $msg ?></li>
				<? endforeach; ?>
				</ul>
			</div>
			<? endif; ?>
			
			<?= $this->layout()->content ?>
			
		</div>
		
		

		<? if($this->subMenue): ?>
		<div class="right" id="main_right">
			
			<div id="sidebar">
				
				<?= $this->menue($this->subMenue, array('class' => 'content')); ?>
				
			</div>
		</div>
		<?endif; ?>

		<div class="clearer"></div>

	</div>

	<div id="footer">

		<div class="left">
			<a href="#">Meinsinn.de</a> | <a href="#top">Go to top</a>
		</div>

		<div class="right">Design by <a href="http://arcsin.se/">Arcsin</a> <a href="http://templates.arcsin.se/">Web Templates</a></div>

		<div class="clearer"></div>
	
	</div>

</div>
</body>
</html>



