<h1>Gemeinschafskasse</h1>
<h2>Kontenübersicht</h2>

<table>
  <tr>
    <th>Bewohner</th>
    <th>Kontostand</th>
  </tr>
  <?foreach($this->residents as $resident): ?>
  <tr class="<?= $this->cycle(array('even','odd')) ?>">
    <td><?= $resident->getName() ?></td>
    <td align="right"><?= $this->moneyFormat($resident->getCashAccount()->getBalanceInEuro()); ?></td>
  </tr>
  <?endforeach; ?>
</table>
