<?php echo '<?xml version="1.0" encoding="utf-8"?>'; ?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <author>
    <name>WGOrganizer</name>
  </author>
  <title>WGOrganizer Einkäufe</title>
  
  <entry>
    <title>Titel des Weblog-Eintrags</title>
    <id>urn:uuid:1225cfb8-4ebb-aaaa-80da344efa6a</id>
    <summary>Zusammenfassung des Weblog-Eintrags</summary>
    <content>Volltext des Weblog-Eintrags</content>
  </entry>
  
  <entry>
    <title>Titel des Weblog-Eintrags</title>
    <id>urn:uuid:1225c695-cfb8-4ebb-aaaa-80da344efa6a</id>
    <summary>Zusammenfassung des Weblog-Eintrags</summary>
    <content>Volltext des Weblog-Eintrags</content>
  </entry>
  
  <entry>
    <title>Titel des Weblog-Eintrags</title>
    <id>urn:uu:1225c695-cfb8-4ebb-aaaa-80da344efa6a</id>
    <summary>Zusammenfassung des Weblog-Eintrags</summary>
    <content>Volltext des Weblog-Eintrags</content>
  </entry>
</feed>
