<div class="post">
<h1>Einkäufe</h1>
<h2>Die letzten <?= $this->amount ?> Einkäufe</h2>

<div class="body">
<table class="buyingsList">
  <tr>
  	<th>Preis</th>
    <th>Beschreibung</th>
    <th>Datum</th>
    <th>Bewohner</th>
  </tr>
  <?foreach($this->resentBuyings as $buying): ?>
  <tr class="<?= $this->cycle(array('even','odd')) ?>">
    <td><?= sprintf("%.2f", ($buying->price / 100)); ?> €</td>
    <td><?= $buying->description; ?></td>
    <td><? $date = new Zend_Date($buying->bought_at); echo $date->toString('EEEE dd.MM.YY')."<br>".$date->toString('HH:mm');?> Uhr</td>
    <td><?= $buying->getResident()->getName(); ?></td>
  </tr>
  <? endforeach; ?>
</table>
</div>
</div>