<?php /*echo '<?xml version="1.0" encoding="utf-8"?>'; ?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <author>
    <name>WGOrganizer</name>
  </author>
  <title>WGOrganizer Einkäufe</title>
  
  <entry>
    <title>Titel des Weblog-Eintrags</title>
    <id>urn:uuid:1225cfb8-4ebb-aaaa-80da344efa6a</id>
    <summary>Zusammenfassung des Weblog-Eintrags</summary>
    <content>Volltext des Weblog-Eintrags</content>
  </entry>
  
  <entry>
    <title>Titel des Weblog-Eintrags</title>
    <id>urn:uuid:1225c695-cfb8-4ebb-aaaa-80da344efa6a</id>
    <summary>Zusammenfassung des Weblog-Eintrags</summary>
    <content>Volltext des Weblog-Eintrags</content>
  </entry>
  
  <entry>
    <title>Titel des Weblog-Eintrags</title>
    <id>urn:uu:1225c695-cfb8-4ebb-aaaa-80da344efa6a</id>
    <summary>Zusammenfassung des Weblog-Eintrags</summary>
    <content>Volltext des Weblog-Eintrags</content>
  </entry>
</feed>
<?php
*/
 $xml = new xmlWriter();
 $xml->openMemory();
 $xml->setIndent(true);
 $xml->startDocument('1.0','UTF-8');
 $xml->startElementNS(null, 'feed','http://www.w3.org/2005/Atom');

 // Print default information 
 $xml->startElement('author');
 $xml->startElement('name');
 $xml->text('WG-Organizer');
 $xml->endElement();
 $xml->endElement();
 
 $xml->writeElement('title', 'WG-Organizer Buyings Feed');
 $xml->writeElement('id', 'urn:uuid:not_so_uuid');
 
 $xml->startElement('link');
 $xml->writeAttribute('rel', 'self');
 $xml->writeAttribute('href', $this->basepath . 'buyings/index/format/atom/appauth_key/' . $this->currentResident->getAppAuthKey() . '/');
 $xml->endElement();
 
 $xml->startElement('link');
 $xml->writeAttribute('href', $this->basepath);
 $xml->endElement();
 
 // Updated
 $buying = $this->recentBuyings[0];
 $date = new Zend_Date($buying->getBoughtAt());
 $xml->writeElement('updated', $date->get('ATOM'));
 unset($buying);
 
 // Print bought infos
 foreach ( $this->recentBuyings as $buying) {
 	$xml->startElement('entry');
 	
 	$xml->writeElement('title', $buying->getDescription());
 	$xml->writeElement('id', $this->basepath . 'buyings/show/' . $buying->getId());

 	$xml->startElement('link');
 	$xml->writeAttribute('href', $this->basepath . 'buyings/show/' . $buying->getId());
 	$xml->endElement();
 	
 	$dateFmt = new Zend_Date($buying->getBoughtAt());
 	$xml->writeElement('updated', $dateFmt->get('ATOM'));
 	
 	$xml->startElement('summary');
 	$xml->writeAttribute('type', 'html');
 	$xml->text(sprintf("%s kaufte %s für %s", $buying->getResident()->getName(), $buying->getDescription(), $this->moneyFormat($buying->getPrice())));
 	$xml->endElement();
 	
 	$xml->startElement('content');
 	$xml->writeAttribute('type', 'html');
 	$xml->text(sprintf("Datum: %s<br />Bewohner: %s<br />Artikel: %s<br />Preis: %s<br />", 
 				$this->dateFormat($buying->getBoughtAt()),
 				$buying->getResident()->getName(),
 				$buying->getDescription(),
 				$this->moneyFormat($buying->getPrice())		
 	));
 	$xml->endElement();
 	$xml->endElement();
 }
 
 $xml->endElement();
 echo $xml->outputMemory(true);

